version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password123
    ports: 
      - '5432:5432'
    volumes:
      - api-postgres:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./api:/opt/app
      - bundler_gems:/bundle
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.react
    volumes:
      - ./app:/opt/app
    ports:
      - '4000:3000'
    env_file:
      - .env
volumes:
  api-postgres:
  bundler_gems: