require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_shelves", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # BookShelf. As you add validations to BookShelf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Shelf 1" }
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BookShelvesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookShelf.create! valid_attributes
      get book_shelves_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_shelf = BookShelf.create! valid_attributes
      get book_shelf_url(book_shelf), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookShelf" do
        expect {
          post book_shelves_url,
               params: { book_shelf: valid_attributes }, headers: valid_headers, as: :json
        }.to change(BookShelf, :count).by(1)
      end

      it "renders a JSON response with the new book_shelf" do
        post book_shelves_url,
             params: { book_shelf: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookShelf" do
        expect {
          post book_shelves_url,
               params: { book_shelf: invalid_attributes }, as: :json
        }.to change(BookShelf, :count).by(0)
      end

      it "renders a JSON response with errors for the new book_shelf" do
        post book_shelves_url,
             params: { book_shelf: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Shelf 2" }
      }

      it "updates the requested book_shelf" do
        book_shelf = BookShelf.create! valid_attributes
        patch book_shelf_url(book_shelf),
              params: { book_shelf: new_attributes }, headers: valid_headers, as: :json
        book_shelf.reload
        expect(book_shelf.name).to eq(new_attributes[:name])
      end

      it "renders a JSON response with the book_shelf" do
        book_shelf = BookShelf.create! valid_attributes
        patch book_shelf_url(book_shelf),
              params: { book_shelf: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the book_shelf" do
        book_shelf = BookShelf.create! valid_attributes
        patch book_shelf_url(book_shelf),
              params: { book_shelf: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_shelf" do
      book_shelf = BookShelf.create! valid_attributes
      expect {
        delete book_shelf_url(book_shelf), headers: valid_headers, as: :json
      }.to change(BookShelf, :count).by(-1)
    end
  end
end
